---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - epam.com
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epam.com
  resources:
  - webs/finalizers
  verbs:
  - update
- apiGroups:
  - epam.com
  resources:
  - webs/status
  verbs:
  - get
  - patch
  - update
