# permissions for end users to edit webs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: web-operator
    app.kubernetes.io/managed-by: kustomize
  name: web-editor-role
rules:
- apiGroups:
  - epam.com
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epam.com
  resources:
  - webs/status
  verbs:
  - get
